site: Intersection of Universes
title: IoU
description: >-
  Intersection of Universes (Benjamin Efrati & Shu Isaka)
googlewebfonts: Fira+Code:wght@400;500;700
lang: en-US
timezone: Rome
repo: https://github.com/p0wex/Gesko # site repo [optional]
data-theme: dark # default theme "dark" | "light"

author:
  name: IoU
  bio: A nomadic artwork in progress. Installation, performance, art game, VR, EEG sensor,2021.
  username: IoU # general username
  github: metaleptic # github username
  twitter: metalepticgames # twitter username
  email: intersectionofuniverses@gmail.com # email adress

# URL settings
url: "https://iou.center" #
baseurl: "/IoU" # leave blank if not wishd
permalink: "https://iou.center"
permalink: iou 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     true
  collections: false


